name: Website Monitor

on:
  schedule:
    - cron: "*/2 * * * *"  # Every 2 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check Website Status
        run: |
          URL="https://occ.osidigital.com"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" $URL)
          echo "Website returned status: $STATUS"

          if [ "$STATUS" -ne 200 ]; then
            echo "Website is DOWN! Status: $STATUS"
          fi
